---
namespace: hadoop

stack:
  defines: process-group
  metadata:
    name: Hadoop
    description: |
      Hadoop is a widely used open-source framework designed for distributed storage and processing of large datasets. It provides a highly scalable and fault-tolerant platform for storing and processing big data using commodity hardware.

      At its core, Hadoop consists of two main components: the Hadoop Distributed File System (HDFS) and MapReduce. HDFS is a distributed file system that stores data across multiple nodes in a cluster, while MapReduce is a programming model for processing large datasets in parallel across the cluster.

      Hadoop is highly versatile and can handle a wide range of data types, from structured to unstructured, including text, images, and videos. It also offers a variety of tools and APIs for data processing, such as Hive, Pig, and Spark.

      Hadoop has become an essential tool in the field of big data and is used by many organizations to manage and analyze vast amounts of data efficiently and cost-effectively. Its flexibility, scalability, and fault tolerance make it a popular choice for data-driven applications in industries such as finance, healthcare, and retail.

      ---

      Notes:

      | Variable     | Description      | Default                 |
      | ------------ | ---------------- | ----------------------- |
      | image_tag    | Image tag to use | 3.2.1-hadoop3.2.1-java8 |
      | cluster_name | Cluster Name     | Monk SuperCluster       |

    website: https://hadoop.apache.org/
    publisher: monk.io
    icon: https://hadoop.apache.org/elephant.png
    source: https://github.com/apache/hadoop
    tags: data-driven applications, data processing, data storage, apache, pig, spark, big data, data analytics, scalability, hadoop, fault tolerance, mapreduce, hive, distributed computing, hdfs, open source
    license: Apache License 2.0
  runnable-list:
    - hadoop/hadoop-name-node
    - hadoop/hadoop-data-node
    - hadoop/hadoop-resource-manager-node
    - hadoop/hadoop-node-manager
    - hadoop/hadoop-history-manager-node
  variables:
    image_tag:
      type: string
      value: 3.2.1-hadoop3.2.1-java8
    cluster_name:
      type: string
      value: Monk SuperCluster
